### ISSUE TITLE
【bug】使用test调用后报错，KeyError: 'success' 

### ISSUE THREAD

**Issue by Ikaros-521** [xw5xr6/revTongYi#3]
```
Traceback (most recent call last):
  File "F:\github_pro\test\ali.py", line 32, in <module>
    test()
  File "F:\github_pro\test\ali.py", line 23, in test
    sess = revTongYi.Session(
  File "D:\Miniconda3\lib\site-packages\revTongYi\__init__.py", line 90, in __init__
    if resp_json['success']:
KeyError: 'success'
```

解析不对了，是不是不更新了

**Comment by Ikaros-521** [comment]
```
{'timestamp': '2023-09-14T09:25:14.059+00:00', 'status': 404, 'error': 'Not Found', 'message': '', 'path': '/qianwen/addSession'}
```

**Comment by xw5xr6** [comment]
已恢复，请使用
```bash
pip install -U revTongYi
```
更新到最新版后使用

**Comment by Ikaros-521** [comment]
> 已恢复，请使用
> 
> ```shell
> pip install -U revTongYi
> ```
> 
> 更新到最新版后使用

仍然无效
![image](https://github.com/xw5xr6/revTongYi/assets/40910637/83312f4d-7d05-44f7-9ca2-a0596c57b087)

**Comment by Ikaros-521** [comment]
好吧 版本搞错了
